name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar archivos
        run: |
          test -f index.html
          test -f script.js

      - name: Validar HTML básico
        run: |
          grep "<html" index.html
          grep "</html>" index.html

      - name: Validar JS
        run: |
          node --check script.js

      - name: CI Exitosa
        run: echo "Todo OK"